# Generated by Django 3.1.1 on 2021-04-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0003_auto_20210411_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstaProfiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessName', models.CharField(max_length=200)),
                ('InstagramUserName', models.CharField(max_length=200)),
                ('InstagramPassword', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Province', models.CharField(max_length=200)),
                ('PostalCode', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Profiles',
        ),
    ]
