# Generated by Django 3.1.1 on 2021-04-27 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_auto_20210426_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='instaprofiles',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
